# Generated by Django 3.2.4 on 2021-08-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('clock_in', models.TimeField(null=True)),
                ('clock_out', models.TimeField(null=True)),
                ('total_work_duration', models.TimeField(null=True)),
                ('status', models.SlugField()),
            ],
        ),
    ]
