# Generated by Django 3.2.5 on 2021-08-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance1_total_work_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance1',
            name='total_work_duration',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
