# Generated by Django 3.2.4 on 2021-08-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('Trainee Software Engineer', 'Trainee Software Engineer'), ('Trainer', 'Trainer')], max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
