# Generated by Django 3.2.5 on 2021-08-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_leave_type', models.CharField(choices=[('causal leave', 'Causal Leave'), ('loss of pay', 'Loss Of Pay'), ('sick leave', 'Sick Leave')], max_length=50)),
                ('start_date_from', models.DateField()),
                ('start_date_to', models.DateField()),
                ('message', models.TextField()),
                ('attachment', models.FileField(upload_to='')),
            ],
        ),
    ]
