# Generated by Django 3.2.5 on 2021-08-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemodel',
            name='attachment',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
